### ISSUE TITLE
How to make application permission requests

### ISSUE THREAD

**Issue by JonoSuave** [dwarfered/msal-react-quickstart#1]
Is there a way to make server side application permission Graph requests (e.g. get Entra id users, create an item on a SharePoint list, etc.)? These would be actions that the signed in user may not have permissions for, which is why it would be done under application Graph api permissions.

**Comment by dwarfered** [comment]
That would be giving the App Registration application permissions. Unlike delegated permissions, which run under the context of the signed-in user and are limited to that user’s permissions, application permissions run under the context of the application and can perform actions independently of the user’s permissions. This allows the application to access resources or perform actions that the signed-in user might not have permission for. You would not use a Single Page Application for this scenario though.

**Comment by JonoSuave** [comment]
How would you recommend the list items the user only has view access to be updated or created then?

**Comment by dwarfered** [comment]
On your app-reg for your application you'd add Delegated permission Sites.Selected 
Then ask your SharePoint admin to add the appropriate role listed:
https://devblogs.microsoft.com/microsoft365dev/sharepoint-now-supports-delegated-sites-selected-authentication/

When signed in to your app, this would allow them to see and add items, as they can when they view the SharePoint site itself.
